$base = "C:\GABARITO\capas\fast\src\main\java\com\fastjava\core"
New-Item -ItemType Directory -Force -Path $base | Out-Null

# ===== FastJava.java =====
$fj = [System.Text.StringBuilder]::new()
$null = $fj.AppendLine('package com.fastjava.core;')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('import com.sun.net.httpserver.*;')
$null = $fj.AppendLine('import java.io.*;')
$null = $fj.AppendLine('import java.lang.annotation.*;')
$null = $fj.AppendLine('import java.lang.reflect.*;')
$null = $fj.AppendLine('import java.net.*;')
$null = $fj.AppendLine('import java.nio.charset.StandardCharsets;')
$null = $fj.AppendLine('import java.security.*;')
$null = $fj.AppendLine('import java.time.*;')
$null = $fj.AppendLine('import java.time.format.DateTimeFormatter;')
$null = $fj.AppendLine('import java.util.*;')
$null = $fj.AppendLine('import java.util.concurrent.*;')
$null = $fj.AppendLine('import java.util.stream.*;')
$null = $fj.AppendLine('import javax.crypto.*;')
$null = $fj.AppendLine('import javax.crypto.spec.*;')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('class Log {')
$null = $fj.AppendLine('    public enum Level { DEBUG, INFO, WARN, ERROR, FATAL }')
$null = $fj.AppendLine('    private static final Level MIN_LEVEL;')
$null = $fj.AppendLine('    private static final boolean USE_COLORS;')
$null = $fj.AppendLine('    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS");')
$null = $fj.AppendLine('    static {')
$null = $fj.AppendLine('        String lvl = System.getenv("LOG_LEVEL");')
$null = $fj.AppendLine('        Level parsed = Level.INFO;')
$null = $fj.AppendLine('        if (lvl != null) { try { parsed = Level.valueOf(lvl.toUpperCase()); } catch (Exception ignored) {} }')
$null = $fj.AppendLine('        MIN_LEVEL = parsed;')
$null = $fj.AppendLine('        USE_COLORS = (System.getenv("NO_COLOR") == null);')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    private static final Map<Level,String> ANSI = Map.of(')
$null = $fj.AppendLine('        Level.DEBUG,"\u001B[36m",Level.INFO,"\u001B[32m",Level.WARN,"\u001B[33m",Level.ERROR,"\u001B[31m",Level.FATAL,"\u001B[35m");')
$null = $fj.AppendLine('    private static final String RESET = "\u001B[0m";')
$null = $fj.AppendLine('    private static String fmt(String tpl, Object... args) {')
$null = $fj.AppendLine('        if (args == null || args.length == 0) return tpl;')
$null = $fj.AppendLine('        StringBuilder sb = new StringBuilder(); int ai = 0, i = 0;')
$null = $fj.AppendLine('        while (i < tpl.length()) {')
$null = $fj.AppendLine('            if (i+1 < tpl.length() && tpl.charAt(i)=='"'"'{"'"'"' && tpl.charAt(i+1)=='"'"'}"'"'") { sb.append(ai < args.length ? args[ai++] : "{}"); i += 2; }')
$null = $fj.AppendLine('            else sb.append(tpl.charAt(i++));')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        return sb.toString();')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    private static String caller() {')
$null = $fj.AppendLine('        for (StackTraceElement e : Thread.currentThread().getStackTrace()) {')
$null = $fj.AppendLine('            String c = e.getClassName();')
$null = $fj.AppendLine('            if (!c.equals("com.fastjava.core.Log") && !c.equals("java.lang.Thread")) {')
$null = $fj.AppendLine('                String s = c.contains(".") ? c.substring(c.lastIndexOf(".")+1) : c;')
$null = $fj.AppendLine('                return s + ":" + e.getLineNumber();')
$null = $fj.AppendLine('            }')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        return "?";')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    private static void log(Level level, String msg, Throwable t) {')
$null = $fj.AppendLine('        if (level.ordinal() < MIN_LEVEL.ordinal()) return;')
$null = $fj.AppendLine('        String ts = LocalDateTime.now().format(FMT), src = caller(), lbl = String.format("%-5s", level.name());')
$null = $fj.AppendLine('        PrintStream out = level.ordinal() >= Level.ERROR.ordinal() ? System.err : System.out;')
$null = $fj.AppendLine('        if (USE_COLORS) out.printf("%s %s[%s]%s [%s] %s%n", ts, ANSI.getOrDefault(level,""), lbl, RESET, src, msg);')
$null = $fj.AppendLine('        else            out.printf("%s [%s] [%s] %s%n", ts, lbl, src, msg);')
$null = $fj.AppendLine('        if (t != null) t.printStackTrace(out);')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    private static Object[] splitT(Object[] args, Throwable[] out) {')
$null = $fj.AppendLine('        if (args.length > 0 && args[args.length-1] instanceof Throwable t) { out[0]=t; return Arrays.copyOf(args,args.length-1); } return args;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    public static void debug(String m, Object... a) { log(Level.DEBUG, fmt(m,a), null); }')
$null = $fj.AppendLine('    public static void info (String m, Object... a) { log(Level.INFO,  fmt(m,a), null); }')
$null = $fj.AppendLine('    public static void warn (String m, Object... a) { log(Level.WARN,  fmt(m,a), null); }')
$null = $fj.AppendLine('    public static void error(String m, Object... a) { Throwable[] t={null}; Object[] r=splitT(a,t); log(Level.ERROR,fmt(m,r),t[0]); }')
$null = $fj.AppendLine('    public static void fatal(String m, Object... a) { Throwable[] t={null}; Object[] r=splitT(a,t); log(Level.FATAL,fmt(m,r),t[0]); }')
$null = $fj.AppendLine('}')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.TYPE)      @interface Controller  { String value() default ""; }')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.TYPE)      @interface Service     {}')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.FIELD)     @interface Inject      {}')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD)    @interface GET         {}')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD)    @interface POST        {}')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD)    @interface PUT         {}')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD)    @interface DELETE      {}')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD)    @interface PATCH       {}')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD)    @interface Path        { String value(); }')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.PARAMETER) @interface PathParam   { String value(); }')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.PARAMETER) @interface QueryParam  { String value(); String defaultValue() default ""; }')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.PARAMETER) @interface Body        {}')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.PARAMETER) @interface Header      { String value(); }')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD)    @interface Authenticated {}')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.METHOD)    @interface RateLimit   { int requests() default 100; int windowSeconds() default 60; }')
$null = $fj.AppendLine('@Retention(RetentionPolicy.RUNTIME) @Target(ElementType.FIELD)     @interface Field       {')
$null = $fj.AppendLine('    String name() default ""; boolean required() default false;')
$null = $fj.AppendLine('    int minLength() default 0; int maxLength() default Integer.MAX_VALUE;')
$null = $fj.AppendLine('    String pattern() default ""; String description() default "";')
$null = $fj.AppendLine('}')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('class HttpException        extends RuntimeException { final int status; HttpException(int s,String m){super(m);status=s;} }')
$null = $fj.AppendLine('class NotFoundException    extends HttpException    { NotFoundException(String m)    {super(404,m);} }')
$null = $fj.AppendLine('class BadRequestException  extends HttpException    { BadRequestException(String m)  {super(400,m);} }')
$null = $fj.AppendLine('class UnauthorizedException extends HttpException   { UnauthorizedException(String m){super(401,m);} }')
$null = $fj.AppendLine('class ForbiddenException   extends HttpException    { ForbiddenException(String m)   {super(403,m);} }')
$null = $fj.AppendLine('class ConflictException    extends HttpException    { ConflictException(String m)    {super(409,m);} }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('class Json {')
$null = $fj.AppendLine('    static String escape(String s) {')
$null = $fj.AppendLine('        if(s==null) return "null";')
$null = $fj.AppendLine('        return "\""+s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r").replace("\t","\\t")+"\"";')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    static Map<String,Object> parse(String json) {')
$null = $fj.AppendLine('        Map<String,Object> map=new LinkedHashMap<>();')
$null = $fj.AppendLine('        if(json==null||json.isBlank()) return map;')
$null = $fj.AppendLine('        json=json.trim(); if(!json.startsWith("{")) return map;')
$null = $fj.AppendLine('        json=json.substring(1,json.lastIndexOf('"'"'}"'"')).trim(); int i=0;')
$null = $fj.AppendLine('        while(i<json.length()){')
$null = $fj.AppendLine('            while(i<json.length()&&json.charAt(i)!='"'"'"'"'"') i++; if(i>=json.length()) break;')
$null = $fj.AppendLine('            int ks=++i; while(i<json.length()&&json.charAt(i)!='"'"'"'"'"') i++;')
$null = $fj.AppendLine('            String key=json.substring(ks,i++);')
$null = $fj.AppendLine('            while(i<json.length()&&json.charAt(i)!='"'"':"'"'"') i++; i++;')
$null = $fj.AppendLine('            while(i<json.length()&&Character.isWhitespace(json.charAt(i))) i++;')
$null = $fj.AppendLine('            if(i>=json.length()) break; char c=json.charAt(i);')
$null = $fj.AppendLine('            if(c=='"'"'"'"'"'"){int vs=++i; while(i<json.length()&&json.charAt(i)!='"'"'"'"'"'"){if(json.charAt(i)=='"'"'\\"'"'"') i++;i++;} map.put(key,json.substring(vs,i++));}')
$null = $fj.AppendLine('            else if(c=='"'"'t"'"'"'||c=='"'"'f"'"'"'){boolean v=c=='"'"'t"'"'"';i+=v?4:5;map.put(key,v);}')
$null = $fj.AppendLine('            else if(c=='"'"'n"'"'"'){i+=4;map.put(key,null);}')
$null = $fj.AppendLine('            else{int ns=i;while(i<json.length()&&",}".indexOf(json.charAt(i))<0) i++;')
$null = $fj.AppendLine('                String num=json.substring(ns,i).trim();')
$null = $fj.AppendLine('                try{map.put(key,Long.parseLong(num));}catch(NumberFormatException e2){try{map.put(key,Double.parseDouble(num));}catch(NumberFormatException e3){map.put(key,num);}}}')
$null = $fj.AppendLine('            while(i<json.length()&&json.charAt(i)!='"'"',"'"'"'&&json.charAt(i)!='"'"'}"'"'"') i++;')
$null = $fj.AppendLine('            if(i<json.length()&&json.charAt(i)=='"'"',"'"'"') i++;')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        return map;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    static String toJson(Object obj) {')
$null = $fj.AppendLine('        if(obj==null) return "null";')
$null = $fj.AppendLine('        if(obj instanceof String s) return escape(s);')
$null = $fj.AppendLine('        if(obj instanceof Boolean||obj instanceof Number) return obj.toString();')
$null = $fj.AppendLine('        if(obj instanceof Map<?,?> m) return "{"+m.entrySet().stream().map(e->escape(e.getKey().toString())+":"+toJson(e.getValue())).collect(Collectors.joining(","))+"}";')
$null = $fj.AppendLine('        if(obj instanceof List<?> l) return "["+l.stream().map(Json::toJson).collect(Collectors.joining(","))+"]";')
$null = $fj.AppendLine('        StringBuilder sb=new StringBuilder("{"); boolean first=true;')
$null = $fj.AppendLine('        for(java.lang.reflect.Field f:obj.getClass().getDeclaredFields()){')
$null = $fj.AppendLine('            if(Modifier.isStatic(f.getModifiers())) continue; f.setAccessible(true);')
$null = $fj.AppendLine('            try{if(!first) sb.append(","); sb.append(escape(f.getName())).append(":").append(toJson(f.get(obj))); first=false;}catch(IllegalAccessException ignored){}')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        return sb.append("}").toString();')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('}')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('class Validator {')
$null = $fj.AppendLine('    static List<String> validate(Object obj) {')
$null = $fj.AppendLine('        List<String> errors=new ArrayList<>(); if(obj==null) return errors;')
$null = $fj.AppendLine('        for(java.lang.reflect.Field f:obj.getClass().getDeclaredFields()){')
$null = $fj.AppendLine('            if(!f.isAnnotationPresent(Field.class)) continue;')
$null = $fj.AppendLine('            Field ann=f.getAnnotation(Field.class); f.setAccessible(true);')
$null = $fj.AppendLine('            String fname=ann.name().isEmpty()?f.getName():ann.name();')
$null = $fj.AppendLine('            Object val; try{val=f.get(obj);}catch(IllegalAccessException e){continue;}')
$null = $fj.AppendLine('            if(ann.required()&&(val==null||val.toString().isBlank())) errors.add(fname+" is required");')
$null = $fj.AppendLine('            if(val instanceof String s){')
$null = $fj.AppendLine('                if(s.length()<ann.minLength()) errors.add(fname+" min "+ann.minLength()+" chars");')
$null = $fj.AppendLine('                if(s.length()>ann.maxLength()) errors.add(fname+" max "+ann.maxLength()+" chars");')
$null = $fj.AppendLine('                if(!ann.pattern().isEmpty()&&!s.matches(ann.pattern())) errors.add(fname+" invalid format");')
$null = $fj.AppendLine('            }')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        return errors;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('}')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('class JWT {')
$null = $fj.AppendLine('    private final String secret;')
$null = $fj.AppendLine('    JWT(String secret){this.secret=secret;}')
$null = $fj.AppendLine('    String generate(Map<String,Object> claims){')
$null = $fj.AppendLine('        String header=Base64.getUrlEncoder().withoutPadding().encodeToString("{\"alg\":\"HS256\",\"typ\":\"JWT\"}".getBytes(StandardCharsets.UTF_8));')
$null = $fj.AppendLine('        long now=System.currentTimeMillis()/1000;')
$null = $fj.AppendLine('        Map<String,Object> payload=new LinkedHashMap<>(claims); payload.put("iat",now); payload.put("exp",now+86400);')
$null = $fj.AppendLine('        String ps=Base64.getUrlEncoder().withoutPadding().encodeToString(Json.toJson(payload).getBytes(StandardCharsets.UTF_8));')
$null = $fj.AppendLine('        return header+"."+ps+"."+sign(header+"."+ps);')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    Map<String,Object> verify(String token){')
$null = $fj.AppendLine('        if(token==null||token.isBlank()) throw new UnauthorizedException("Token required");')
$null = $fj.AppendLine('        String[] p=token.split("\\\\."); if(p.length!=3) throw new UnauthorizedException("Invalid token format");')
$null = $fj.AppendLine('        if(!constantTimeEquals(sign(p[0]+"."+p[1]),p[2])) throw new UnauthorizedException("Invalid token signature");')
$null = $fj.AppendLine('        Map<String,Object> claims=Json.parse(new String(Base64.getUrlDecoder().decode(p[1]),StandardCharsets.UTF_8));')
$null = $fj.AppendLine('        Object exp=claims.get("exp");')
$null = $fj.AppendLine('        if(exp instanceof Number n&&n.longValue()<System.currentTimeMillis()/1000) throw new UnauthorizedException("Token expired");')
$null = $fj.AppendLine('        return claims;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    private String sign(String data){')
$null = $fj.AppendLine('        try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return Base64.getUrlEncoder().withoutPadding().encodeToString(mac.doFinal(data.getBytes(StandardCharsets.UTF_8)));}')
$null = $fj.AppendLine('        catch(Exception e){throw new RuntimeException("JWT signing failed",e);}')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    private boolean constantTimeEquals(String a,String b){if(a.length()!=b.length()) return false;int r=0;for(int i=0;i<a.length();i++) r|=a.charAt(i)^b.charAt(i);return r==0;}')
$null = $fj.AppendLine('}')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('class Route {')
$null = $fj.AppendLine('    final String method,pattern; final Method handler; final Object controller;')
$null = $fj.AppendLine('    Route(String method,String pattern,Method handler,Object controller){this.method=method;this.pattern=pattern;this.handler=handler;this.controller=controller;}')
$null = $fj.AppendLine('    boolean matches(String rm,String path,Map<String,String> vars){')
$null = $fj.AppendLine('        if(!this.method.equalsIgnoreCase(rm)) return false;')
$null = $fj.AppendLine('        String[] ps=pattern.split("/"),rs=path.split("/"); if(ps.length!=rs.length) return false;')
$null = $fj.AppendLine('        for(int i=0;i<ps.length;i++){if(ps[i].startsWith(":")) vars.put(ps[i].substring(1),rs[i]); else if(!ps[i].equals(rs[i])) return false;}')
$null = $fj.AppendLine('        return true;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('}')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('public class FastJava {')
$null = $fj.AppendLine('    private final HttpServer server;')
$null = $fj.AppendLine('    private final List<Route> routes=new ArrayList<>();')
$null = $fj.AppendLine('    private final Map<Class<?>,Object> container=new HashMap<>();')
$null = $fj.AppendLine('    private final JWT jwt;')
$null = $fj.AppendLine('    private final Map<String,Deque<Long>> rateLimitWindows=new ConcurrentHashMap<>();')
$null = $fj.AppendLine('    private int port=8080;')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    public FastJava() throws Exception {')
$null = $fj.AppendLine('        String secret=System.getenv("JWT_SECRET");')
$null = $fj.AppendLine('        if(secret==null||secret.isBlank()){secret="my-secret-key-change-in-production";Log.warn("JWT_SECRET nao definida - usando padrao!");}')
$null = $fj.AppendLine('        this.jwt=new JWT(secret); this.server=HttpServer.create();')
$null = $fj.AppendLine('        Log.debug("FastJava criado");')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('    public FastJava port(int p){this.port=p;return this;}')
$null = $fj.AppendLine('    public JWT getJwt(){return jwt;}')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    public FastJava register(Class<?>... classes){')
$null = $fj.AppendLine('        for(Class<?> cls:classes){')
$null = $fj.AppendLine('            try{')
$null = $fj.AppendLine('                Object inst=createInstance(cls); container.put(cls,inst);')
$null = $fj.AppendLine('                if(!cls.isAnnotationPresent(Controller.class)){Log.debug("Service: {}", cls.getSimpleName());continue;}')
$null = $fj.AppendLine('                String base=cls.getAnnotation(Controller.class).value();')
$null = $fj.AppendLine('                for(Method m:cls.getDeclaredMethods()){')
$null = $fj.AppendLine('                    String hm=null;')
$null = $fj.AppendLine('                    if(m.isAnnotationPresent(GET.class)) hm="GET";')
$null = $fj.AppendLine('                    else if(m.isAnnotationPresent(POST.class)) hm="POST";')
$null = $fj.AppendLine('                    else if(m.isAnnotationPresent(PUT.class)) hm="PUT";')
$null = $fj.AppendLine('                    else if(m.isAnnotationPresent(DELETE.class)) hm="DELETE";')
$null = $fj.AppendLine('                    else if(m.isAnnotationPresent(PATCH.class)) hm="PATCH";')
$null = $fj.AppendLine('                    if(hm==null) continue;')
$null = $fj.AppendLine('                    String path=m.isAnnotationPresent(Path.class)?base+m.getAnnotation(Path.class).value():base;')
$null = $fj.AppendLine('                    routes.add(new Route(hm,path,m,inst)); Log.info("Rota: {} {}", hm, path);')
$null = $fj.AppendLine('                }')
$null = $fj.AppendLine('            }catch(Exception e){Log.fatal("Falha ao registrar {}: {}", cls.getSimpleName(), e.getMessage(), e);throw new RuntimeException(e);}')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        return this;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    private Object createInstance(Class<?> cls) throws Exception {')
$null = $fj.AppendLine('        if(container.containsKey(cls)) return container.get(cls);')
$null = $fj.AppendLine('        Object inst=cls.getDeclaredConstructor().newInstance();')
$null = $fj.AppendLine('        for(java.lang.reflect.Field f:cls.getDeclaredFields()){')
$null = $fj.AppendLine('            if(!f.isAnnotationPresent(Inject.class)) continue; f.setAccessible(true);')
$null = $fj.AppendLine('            Object dep=container.get(f.getType());')
$null = $fj.AppendLine('            if(dep==null){dep=createInstance(f.getType());container.put(f.getType(),dep);}')
$null = $fj.AppendLine('            f.set(inst,dep); Log.debug("Inject {} -> {}", f.getType().getSimpleName(), cls.getSimpleName());')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        return inst;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    public void start() throws Exception {')
$null = $fj.AppendLine('        server.bind(new InetSocketAddress(port),0);')
$null = $fj.AppendLine('        server.createContext("/",this::handle);')
$null = $fj.AppendLine('        server.setExecutor(Executors.newVirtualThreadPerTaskExecutor());')
$null = $fj.AppendLine('        server.start();')
$null = $fj.AppendLine('        Log.info("Servidor iniciado na porta {}", port);')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    private void handle(HttpExchange ex){')
$null = $fj.AppendLine('        String method=ex.getRequestMethod(), path=ex.getRequestURI().getPath();')
$null = $fj.AppendLine('        Log.debug("{} {}", method, path);')
$null = $fj.AppendLine('        if("GET".equals(method)&&"/health".equals(path)){sendResponse(ex,200,"{\"status\":\"UP\",\"routes\":"+routes.size()+"}");return;}')
$null = $fj.AppendLine('        if("GET".equals(method)&&"/docs".equals(path)){sendResponse(ex,200,generateOpenApi());return;}')
$null = $fj.AppendLine('        Map<String,String> pathVars=new HashMap<>(), queryParams=parseQueryParams(ex.getRequestURI().getQuery());')
$null = $fj.AppendLine('        Route matched=null; for(Route r:routes){if(r.matches(method,path,pathVars)){matched=r;break;}}')
$null = $fj.AppendLine('        if(matched==null){Log.warn("404: {} {}", method, path);sendResponse(ex,404,"{\"error\":\"Not found: "+method+" "+path+"\"}");return;}')
$null = $fj.AppendLine('        if(matched.handler.isAnnotationPresent(RateLimit.class)){')
$null = $fj.AppendLine('            RateLimit rl=matched.handler.getAnnotation(RateLimit.class);')
$null = $fj.AppendLine('            String key=ex.getRemoteAddress().getAddress().getHostAddress()+":"+matched.pattern;')
$null = $fj.AppendLine('            if(!checkRateLimit(key,rl.requests(),rl.windowSeconds())){Log.warn("Rate limit: {}", key);sendResponse(ex,429,"{\"error\":\"Too many requests\"}");return;}')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        Map<String,Object> claims=null;')
$null = $fj.AppendLine('        if(matched.handler.isAnnotationPresent(Authenticated.class)){')
$null = $fj.AppendLine('            String auth=ex.getRequestHeaders().getFirst("Authorization");')
$null = $fj.AppendLine('            String token=(auth!=null&&auth.startsWith("Bearer "))?auth.substring(7):null;')
$null = $fj.AppendLine('            try{claims=jwt.verify(token);}')
$null = $fj.AppendLine('            catch(HttpException e){Log.warn("Auth falhou: {}", e.getMessage());sendResponse(ex,e.status,"{\"error\":\""+e.getMessage()+"\"}");return;}')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        String body=""; try{body=new String(ex.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);}catch(Exception e){Log.error("Erro ao ler body", e);}')
$null = $fj.AppendLine('        try{')
$null = $fj.AppendLine('            Object[] args=prepareArgs(matched,pathVars,queryParams,body,claims,ex);')
$null = $fj.AppendLine('            Object result;')
$null = $fj.AppendLine('            try{result=matched.handler.invoke(matched.controller,args);}')
$null = $fj.AppendLine('            catch(InvocationTargetException ite){')
$null = $fj.AppendLine('                Throwable cause=ite.getCause();')
$null = $fj.AppendLine('                if(cause instanceof HttpException he) throw he;')
$null = $fj.AppendLine('                Log.error("Handler error: {}", cause!=null?cause.getMessage():"null", cause);')
$null = $fj.AppendLine('                throw new RuntimeException(cause!=null?cause:ite);')
$null = $fj.AppendLine('            }')
$null = $fj.AppendLine('            if(result instanceof CompletableFuture<?> cf){')
$null = $fj.AppendLine('                final String hName=matched.handler.getName();')
$null = $fj.AppendLine('                cf.thenAccept(r->sendResponse(ex,200,Json.toJson(r))).exceptionally(t->{Log.error("Async error {}", hName, t);sendResponse(ex,500,"{\"error\":\"Async error\"}");return null;});')
$null = $fj.AppendLine('            } else { sendResponse(ex,result==null?204:200,result==null?"":Json.toJson(result)); }')
$null = $fj.AppendLine('        }catch(HttpException e){Log.warn("HttpException {}: {}", e.status, e.getMessage());sendResponse(ex,e.status,"{\"error\":\""+e.getMessage()+"\"}");}')
$null = $fj.AppendLine('        catch(Exception e){Log.error("Erro interno {} {}: {}", method, path, e.getMessage(), e);sendResponse(ex,500,"{\"error\":\"Internal server error: "+e.getMessage()+"\"}");}')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    private Object[] prepareArgs(Route route,Map<String,String> pathVars,Map<String,String> queryParams,String body,Map<String,Object> claims,HttpExchange ex) throws Exception {')
$null = $fj.AppendLine('        Parameter[] params=route.handler.getParameters(); Object[] args=new Object[params.length];')
$null = $fj.AppendLine('        for(int i=0;i<params.length;i++){')
$null = $fj.AppendLine('            Parameter p=params[i];')
$null = $fj.AppendLine('            if(p.isAnnotationPresent(PathParam.class)) args[i]=convertToType(pathVars.get(p.getAnnotation(PathParam.class).value()),p.getType());')
$null = $fj.AppendLine('            else if(p.isAnnotationPresent(QueryParam.class)){QueryParam qp=p.getAnnotation(QueryParam.class);String val=queryParams.getOrDefault(qp.value(),qp.defaultValue());if(val==null||val.isEmpty()) val=qp.defaultValue();args[i]=convertToType(val,p.getType());}')
$null = $fj.AppendLine('            else if(p.isAnnotationPresent(Body.class)) args[i]=parseBody(body,p.getType());')
$null = $fj.AppendLine('            else if(p.isAnnotationPresent(Header.class)) args[i]=convertToType(ex.getRequestHeaders().getFirst(p.getAnnotation(Header.class).value()),p.getType());')
$null = $fj.AppendLine('            else if(p.getType()==Map.class) args[i]=claims!=null?claims:new HashMap<>();')
$null = $fj.AppendLine('            else args[i]=null;')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        return args;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    private Object convertToType(String value,Class<?> type){')
$null = $fj.AppendLine('        if(value==null||value.isEmpty()){if(type==int.class||type==Integer.class) return 0;if(type==long.class||type==Long.class) return 0L;if(type==boolean.class||type==Boolean.class) return false;return null;}')
$null = $fj.AppendLine('        try{if(type==String.class) return value;if(type==int.class||type==Integer.class) return Integer.parseInt(value);if(type==long.class||type==Long.class) return Long.parseLong(value);if(type==boolean.class||type==Boolean.class) return Boolean.parseBoolean(value);if(type==double.class||type==Double.class) return Double.parseDouble(value);}')
$null = $fj.AppendLine('        catch(NumberFormatException e){Log.warn("Falha converter {} -> {}", value, type.getSimpleName());}')
$null = $fj.AppendLine('        return value;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    private Object parseBody(String body,Class<?> type){')
$null = $fj.AppendLine('        if(body==null||body.isBlank()) return null;')
$null = $fj.AppendLine('        if(type==String.class) return body;')
$null = $fj.AppendLine('        if(type==Map.class) return Json.parse(body);')
$null = $fj.AppendLine('        try{')
$null = $fj.AppendLine('            Map<String,Object> map=Json.parse(body); Object inst=type.getDeclaredConstructor().newInstance();')
$null = $fj.AppendLine('            for(java.lang.reflect.Field f:type.getDeclaredFields()){')
$null = $fj.AppendLine('                if(Modifier.isStatic(f.getModifiers())) continue; f.setAccessible(true);')
$null = $fj.AppendLine('                Object val=map.get(f.getName()); if(val==null) continue;')
$null = $fj.AppendLine('                if(f.getType()==int.class||f.getType()==Integer.class) val=val instanceof Number n?n.intValue():Integer.parseInt(val.toString());')
$null = $fj.AppendLine('                else if(f.getType()==long.class||f.getType()==Long.class) val=val instanceof Number n?n.longValue():Long.parseLong(val.toString());')
$null = $fj.AppendLine('                else if(f.getType()==double.class||f.getType()==Double.class) val=val instanceof Number n?n.doubleValue():Double.parseDouble(val.toString());')
$null = $fj.AppendLine('                else if(f.getType()==boolean.class||f.getType()==Boolean.class) val=val instanceof Boolean b?b:Boolean.parseBoolean(val.toString());')
$null = $fj.AppendLine('                f.set(inst,val);')
$null = $fj.AppendLine('            }')
$null = $fj.AppendLine('            List<String> errors=Validator.validate(inst);')
$null = $fj.AppendLine('            if(!errors.isEmpty()){Log.warn("Validacao falhou: {}", errors);throw new BadRequestException("Validation failed: "+String.join(", ",errors));}')
$null = $fj.AppendLine('            return inst;')
$null = $fj.AppendLine('        }catch(HttpException e){throw e;}')
$null = $fj.AppendLine('        catch(Exception e){Log.error("Erro parseBody: {}", e.getMessage(), e);throw new BadRequestException("Invalid body: "+e.getMessage());}')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    private Map<String,String> parseQueryParams(String query){')
$null = $fj.AppendLine('        Map<String,String> p=new HashMap<>(); if(query==null||query.isBlank()) return p;')
$null = $fj.AppendLine('        for(String pair:query.split("&")){String[] kv=pair.split("=",2);if(kv.length==2){try{p.put(URLDecoder.decode(kv[0],StandardCharsets.UTF_8),URLDecoder.decode(kv[1],StandardCharsets.UTF_8));}catch(Exception e){p.put(kv[0],kv[1]);}}}')
$null = $fj.AppendLine('        return p;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    private boolean checkRateLimit(String key,int max,int windowSec){')
$null = $fj.AppendLine('        long now=System.currentTimeMillis(); long windowMs=windowSec*1000L;')
$null = $fj.AppendLine('        Deque<Long> ts=rateLimitWindows.computeIfAbsent(key,k->new ArrayDeque<>());')
$null = $fj.AppendLine('        synchronized(ts){while(!ts.isEmpty()&&now-ts.peekFirst()>windowMs) ts.pollFirst();if(ts.size()>=max) return false;ts.addLast(now);}')
$null = $fj.AppendLine('        return true;')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    private void sendResponse(HttpExchange ex,int status,String body){')
$null = $fj.AppendLine('        try{byte[] bytes=body.getBytes(StandardCharsets.UTF_8);ex.getResponseHeaders().set("Content-Type","application/json; charset=UTF-8");ex.getResponseHeaders().set("Access-Control-Allow-Origin","*");ex.sendResponseHeaders(status,bytes.length);try(OutputStream os=ex.getResponseBody()){os.write(bytes);}Log.debug("Response {} ({} bytes)", status, bytes.length);}')
$null = $fj.AppendLine('        catch(Exception e){Log.error("Erro sendResponse: {}", e.getMessage(), e);}')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('')
$null = $fj.AppendLine('    private String generateOpenApi(){')
$null = $fj.AppendLine('        StringBuilder sb=new StringBuilder("{\"openapi\":\"3.0.0\",\"info\":{\"title\":\"FastJava API\",\"version\":\"2.0\"},\"paths\":{");')
$null = $fj.AppendLine('        Map<String,List<Route>> grouped=new LinkedHashMap<>(); for(Route r:routes) grouped.computeIfAbsent(r.pattern,k->new ArrayList<>()).add(r);')
$null = $fj.AppendLine('        boolean fr=true;')
$null = $fj.AppendLine('        for(Map.Entry<String,List<Route>> e:grouped.entrySet()){')
$null = $fj.AppendLine('            if(!fr) sb.append(","); sb.append(Json.escape(e.getKey())).append(":{"); boolean fm=true;')
$null = $fj.AppendLine('            for(Route r:e.getValue()){if(!fm) sb.append(",");sb.append("\"").append(r.method.toLowerCase()).append("\":{\"operationId\":\"").append(r.handler.getName()).append("\",\"security\":[");if(r.handler.isAnnotationPresent(Authenticated.class)) sb.append("{\"bearerAuth\":[]}");sb.append("]}");fm=false;}')
$null = $fj.AppendLine('            sb.append("}"); fr=false;')
$null = $fj.AppendLine('        }')
$null = $fj.AppendLine('        return sb.append("}}").toString();')
$null = $fj.AppendLine('    }')
$null = $fj.AppendLine('}')

[System.IO.File]::WriteAllText("$base\FastJava.java", $fj.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Host "FastJava.java criado! ($($fj.Length) chars)"

# ===== ExampleApplication.java =====
$ex = [System.Text.StringBuilder]::new()
$null = $ex.AppendLine('package com.fastjava.core;')
$null = $ex.AppendLine('import java.util.*;')
$null = $ex.AppendLine('import java.util.concurrent.*;')
$null = $ex.AppendLine('import java.util.concurrent.atomic.*;')
$null = $ex.AppendLine('')
$null = $ex.AppendLine('class User {')
$null = $ex.AppendLine('    @Field(name="username", required=true, minLength=3, maxLength=50) String username;')
$null = $ex.AppendLine('    @Field(name="email",    required=true, pattern="^[^@]+@[^@]+\\.[^@]+$") String email;')
$null = $ex.AppendLine('    @Field(name="password", required=true, minLength=6) String password;')
$null = $ex.AppendLine('    String role="USER"; long id; String createdAt;')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('class UserResponse {')
$null = $ex.AppendLine('    long id; String username, email, role, createdAt;')
$null = $ex.AppendLine('    UserResponse(User u){id=u.id;username=u.username;email=u.email;role=u.role;createdAt=u.createdAt;}')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('class Product {')
$null = $ex.AppendLine('    @Field(name="name",     required=true, minLength=2) String name;')
$null = $ex.AppendLine('    @Field(name="price",    required=true) double price;')
$null = $ex.AppendLine('    @Field(name="category", required=true) String category;')
$null = $ex.AppendLine('    String description; int stock; long id; String createdAt;')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('class LoginRequest {')
$null = $ex.AppendLine('    @Field(name="username", required=true) String username;')
$null = $ex.AppendLine('    @Field(name="password", required=true) String password;')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('')
$null = $ex.AppendLine('@Service')
$null = $ex.AppendLine('class JwtProvider {')
$null = $ex.AppendLine('    private final JWT jwt;')
$null = $ex.AppendLine('    JwtProvider(){')
$null = $ex.AppendLine('        String secret=System.getenv("JWT_SECRET");')
$null = $ex.AppendLine('        if(secret==null||secret.isBlank()) secret="my-secret-key-change-in-production";')
$null = $ex.AppendLine('        this.jwt=new JWT(secret);')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('    String generate(Map<String,Object> claims){return jwt.generate(claims);}')
$null = $ex.AppendLine('    Map<String,Object> verify(String token){return jwt.verify(token);}')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('')
$null = $ex.AppendLine('@Service')
$null = $ex.AppendLine('class UserService {')
$null = $ex.AppendLine('    private final Map<Long,User> db=new ConcurrentHashMap<>();')
$null = $ex.AppendLine('    private final AtomicLong nextId=new AtomicLong(1);')
$null = $ex.AppendLine('    List<User> findAll(String search){')
$null = $ex.AppendLine('        if(search==null||search.isBlank()) return new ArrayList<>(db.values());')
$null = $ex.AppendLine('        String q=search.toLowerCase();')
$null = $ex.AppendLine('        return db.values().stream().filter(u->u.username.toLowerCase().contains(q)||u.email.toLowerCase().contains(q)).toList();')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('    User findById(long id){User u=db.get(id);if(u==null) throw new NotFoundException("User not found: "+id);return u;}')
$null = $ex.AppendLine('    User findByUsername(String username){return db.values().stream().filter(u->u.username.equals(username)).findFirst().orElse(null);}')
$null = $ex.AppendLine('    User create(User user){')
$null = $ex.AppendLine('        if(db.values().stream().anyMatch(u->u.username.equals(user.username)||u.email.equals(user.email))) throw new ConflictException("Username or email already exists");')
$null = $ex.AppendLine('        user.id=nextId.getAndIncrement();user.createdAt=java.time.Instant.now().toString();db.put(user.id,user);')
$null = $ex.AppendLine('        Log.info("User criado: id={} username={}", user.id, user.username);return user;')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('    User update(long id,User u){User ex=findById(id);if(u.username!=null&&!u.username.isBlank()) ex.username=u.username;if(u.email!=null&&!u.email.isBlank()) ex.email=u.email;if(u.role!=null&&!u.role.isBlank()) ex.role=u.role;db.put(id,ex);return ex;}')
$null = $ex.AppendLine('    void delete(long id){findById(id);db.remove(id);Log.info("User removido: id={}", id);}')
$null = $ex.AppendLine('    boolean validatePassword(User user,String pwd){return user.password.equals(pwd);}')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('')
$null = $ex.AppendLine('@Service')
$null = $ex.AppendLine('class ProductService {')
$null = $ex.AppendLine('    private final Map<Long,Product> db=new ConcurrentHashMap<>();')
$null = $ex.AppendLine('    private final AtomicLong nextId=new AtomicLong(1);')
$null = $ex.AppendLine('    List<Product> findAll(String category,String search){')
$null = $ex.AppendLine('        return db.values().stream()')
$null = $ex.AppendLine('            .filter(p->category==null||category.isBlank()||p.category.equalsIgnoreCase(category))')
$null = $ex.AppendLine('            .filter(p->search==null||search.isBlank()||p.name.toLowerCase().contains(search.toLowerCase()))')
$null = $ex.AppendLine('            .toList();')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('    Product findById(long id){Product p=db.get(id);if(p==null) throw new NotFoundException("Product not found: "+id);return p;}')
$null = $ex.AppendLine('    Product create(Product p){p.id=nextId.getAndIncrement();p.createdAt=java.time.Instant.now().toString();db.put(p.id,p);Log.info("Produto criado: id={}", p.id);return p;}')
$null = $ex.AppendLine('    Product update(long id,Product u){Product ex=findById(id);if(u.name!=null&&!u.name.isBlank()) ex.name=u.name;if(u.description!=null) ex.description=u.description;if(u.price>0) ex.price=u.price;if(u.category!=null&&!u.category.isBlank()) ex.category=u.category;if(u.stock>=0) ex.stock=u.stock;db.put(id,ex);return ex;}')
$null = $ex.AppendLine('    void delete(long id){findById(id);db.remove(id);}')
$null = $ex.AppendLine('    Map<String,Object> getStats(){Map<String,Object> s=new LinkedHashMap<>();s.put("totalProducts",(long)db.size());s.put("totalValue",db.values().stream().mapToDouble(p->p.price*p.stock).sum());Map<String,Long> cat=new HashMap<>();db.values().forEach(p->cat.merge(p.category,1L,Long::sum));s.put("byCategory",cat);return s;}')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('')
$null = $ex.AppendLine('@Controller("/api/auth")')
$null = $ex.AppendLine('class AuthController {')
$null = $ex.AppendLine('    @Inject UserService userService;')
$null = $ex.AppendLine('    @Inject JwtProvider jwtProvider;')
$null = $ex.AppendLine('    @POST @Path("/login")')
$null = $ex.AppendLine('    Object login(@Body LoginRequest req){')
$null = $ex.AppendLine('        Log.info("Login: {}", req.username);')
$null = $ex.AppendLine('        User user=userService.findByUsername(req.username);')
$null = $ex.AppendLine('        if(user==null||!userService.validatePassword(user,req.password)) throw new UnauthorizedException("Invalid credentials");')
$null = $ex.AppendLine('        Map<String,Object> claims=new LinkedHashMap<>();claims.put("sub",String.valueOf(user.id));claims.put("username",user.username);claims.put("role",user.role);')
$null = $ex.AppendLine('        String token=jwtProvider.generate(claims);')
$null = $ex.AppendLine('        Map<String,Object> resp=new LinkedHashMap<>();resp.put("token",token);resp.put("user",new UserResponse(user));return resp;')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('    @POST @Path("/register")')
$null = $ex.AppendLine('    Object register(@Body User user){')
$null = $ex.AppendLine('        Log.info("Registro: {}", user.username);')
$null = $ex.AppendLine('        return new UserResponse(userService.create(user));')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('')
$null = $ex.AppendLine('@Controller("/api/users")')
$null = $ex.AppendLine('class UserController {')
$null = $ex.AppendLine('    @Inject UserService userService;')
$null = $ex.AppendLine('    @GET @Authenticated')
$null = $ex.AppendLine('    Object listUsers(@QueryParam(value="search",defaultValue="") String search, Map<String,Object> claims){')
$null = $ex.AppendLine('        Log.info("List users sub={}", claims.get("sub"));')
$null = $ex.AppendLine('        return userService.findAll(search).stream().map(UserResponse::new).toList();')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('    @GET @Path("/:id") @Authenticated')
$null = $ex.AppendLine('    Object getUser(@PathParam("id") long id, Map<String,Object> claims){return new UserResponse(userService.findById(id));}')
$null = $ex.AppendLine('    @PUT @Path("/:id") @Authenticated')
$null = $ex.AppendLine('    Object updateUser(@PathParam("id") long id, @Body User updates, Map<String,Object> claims){return new UserResponse(userService.update(id,updates));}')
$null = $ex.AppendLine('    @DELETE @Path("/:id") @Authenticated')
$null = $ex.AppendLine('    Object deleteUser(@PathParam("id") long id, Map<String,Object> claims){')
$null = $ex.AppendLine('        if(!"ADMIN".equals(claims.get("role"))) throw new ForbiddenException("Admin role required");')
$null = $ex.AppendLine('        userService.delete(id);Map<String,Object> r=new LinkedHashMap<>();r.put("message","User deleted");return r;')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('    @GET @Path("/async/:id") @Authenticated')
$null = $ex.AppendLine('    CompletableFuture<Object> getUserAsync(@PathParam("id") long id, Map<String,Object> claims){')
$null = $ex.AppendLine('        return CompletableFuture.supplyAsync(()->{try{Thread.sleep(100);}catch(Exception e){}return (Object)new UserResponse(userService.findById(id));});')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('')
$null = $ex.AppendLine('@Controller("/api/products")')
$null = $ex.AppendLine('class ProductController {')
$null = $ex.AppendLine('    @Inject ProductService productService;')
$null = $ex.AppendLine('    @GET')
$null = $ex.AppendLine('    Object listProducts(@QueryParam(value="category",defaultValue="") String category, @QueryParam(value="search",defaultValue="") String search){')
$null = $ex.AppendLine('        return productService.findAll(category,search);')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('    @GET @Path("/:id")')
$null = $ex.AppendLine('    Object getProduct(@PathParam("id") long id){return productService.findById(id);}')
$null = $ex.AppendLine('    @POST @Authenticated')
$null = $ex.AppendLine('    Object createProduct(@Body Product p, Map<String,Object> claims){return productService.create(p);}')
$null = $ex.AppendLine('    @PUT @Path("/:id") @Authenticated')
$null = $ex.AppendLine('    Object updateProduct(@PathParam("id") long id, @Body Product u, Map<String,Object> claims){return productService.update(id,u);}')
$null = $ex.AppendLine('    @DELETE @Path("/:id") @Authenticated')
$null = $ex.AppendLine('    Object deleteProduct(@PathParam("id") long id, Map<String,Object> claims){productService.delete(id);Map<String,Object> r=new LinkedHashMap<>();r.put("message","Product deleted");return r;}')
$null = $ex.AppendLine('    @GET @Path("/stats") @Authenticated')
$null = $ex.AppendLine('    Object getStats(Map<String,Object> claims){return productService.getStats();}')
$null = $ex.AppendLine('}')
$null = $ex.AppendLine('')
$null = $ex.AppendLine('public class ExampleApplication {')
$null = $ex.AppendLine('    public static void main(String[] args) throws Exception {')
$null = $ex.AppendLine('        Log.info("Iniciando ExampleApplication...");')
$null = $ex.AppendLine('        FastJava app = new FastJava().port(8080);')
$null = $ex.AppendLine('        app.register(')
$null = $ex.AppendLine('            JwtProvider.class,')
$null = $ex.AppendLine('            UserService.class,')
$null = $ex.AppendLine('            ProductService.class,')
$null = $ex.AppendLine('            AuthController.class,')
$null = $ex.AppendLine('            UserController.class,')
$null = $ex.AppendLine('            ProductController.class')
$null = $ex.AppendLine('        );')
$null = $ex.AppendLine('        app.start();')
$null = $ex.AppendLine('        Log.info("=== API pronta! Porta 8080 ===");')
$null = $ex.AppendLine('        Log.info("POST /api/auth/register  - criar conta");')
$null = $ex.AppendLine('        Log.info("POST /api/auth/login     - login JWT");')
$null = $ex.AppendLine('        Log.info("GET  /api/users          - listar usuarios (JWT)");')
$null = $ex.AppendLine('        Log.info("GET  /api/products       - listar produtos");')
$null = $ex.AppendLine('        Log.info("GET  /health             - health check");')
$null = $ex.AppendLine('        Runtime.getRuntime().addShutdownHook(new Thread(()->Log.info("Servidor encerrado.")));')
$null = $ex.AppendLine('    }')
$null = $ex.AppendLine('}')

[System.IO.File]::WriteAllText("$base\ExampleApplication.java", $ex.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Host "ExampleApplication.java criado! ($($ex.Length) chars)"
Write-Host ""
Write-Host "Verificando arquivos:"
Get-ChildItem $base
Write-Host ""
Write-Host "Compilando..."
Set-Location "C:\GABARITO\capas\fast"
mvn compile exec:java
